### ISSUE TITLE
how to specific customed template?

### ISSUE THREAD

**Issue by rainchen** [pawamoy/git-changelog#5]
expection example:
`$ git-changelog -t ${PWD}/keepachangelog-custom-template`

**Comment by pawamoy** [comment]
Hmm. I made a mistake.

So, for it to work, you'll have to create a directory and put your template inside. The template file must be named `changelog.md` (this is where I was wrong, I only thought about markdown files when templates could be anything).

To use it, you have to use `-t path:DIR` where DIR is the directory you created (you would typically name it `keepachangelog-custom-template`.

I can change the behavior of the option to also accept a single file instead of a directory.

I chose to go with a `path:` prefix because if the custom template has the same name as a built-in one, we could not differentiate it, unless using a relative or absolute path, like `./keepachangelog`, `/dir/keepachangelog`, `C:\dir\keepachangelog`, and it seemed too cumbersome to handle all these cases.

But now I see that I was wrong on this as well, because I could simply reserve the names of the built-in templates (forbid their usage), and/or guess when the argument is a path with `pathlib`.

Please be indulgent, this project is still alpha hehe :sweat_smile: I will **definitely** give it more love, it's just that I don't have much time for it these days!

**Comment by rainchen** [comment]
I figured it out by reading the source code, here are my steps:

1. copy git-changelog/src/templates/keepachangelog to myrepo/templates/keepachangelog
2. cd myrepo/
3.  run`$ git-changelog --style basic --template "path:templates/keepachangelog"`

it's working well, thx buddy!
