### ISSUE TITLE
bug: PEP440 compliant versions are no longer allowed since git-changelog version 2.4.1

### ISSUE THREAD

**Issue by robin-vagner** [pawamoy/git-changelog#79]
### Description of the bug
We have packages with versions such as `0.2.0.post1`, which are [PEP440](https://peps.python.org/pep-0440) compliant versions.

git-changelog worked fine with these before, but since version 2.4.1 we get this error :
```
git-changelog: 0.2.0.post2 is not valid SemVer string
```

I guess the error message is right since our versioning is based on python's pep440 and not semantic versioning, but still I don't think this is desired behavior.

If this was intended, then maybe a command-line argument to specify the versioning pattern would be useful ?

### To Reproduce
Create a tag with a PEP440 specific version (`0.2.0.post1` for example), then run `git-changelog`.

### Full traceback

There is no traceback, just this error message : `git-changelog: 0.2.0.post2 is not valid SemVer string`.

### Environment information
```
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.9.13
- __Environment variables__:
- __Installed packages__:
  - `git-changelog` v2.4.1
```

**Comment by pawamoy** [comment]
Hello, thanks for the report, and very sorry for the breaking change! This comes from here: https://github.com/pawamoy/git-changelog/commit/f191ed7c05029674e52c8ada55e0d9e861c320cc#diff-b4ea8efb43c6c51f5b59739374543530fe358728677ca8203462aacb4d9cfad2R457. Where previously we would only use the `semver` library when bumping versions, we are now using it to compare versions in order to correctly group commits. That was an oversight, and it shows we have missing tests in our test suite :slightly_smiling_face: 

I'll fix this asap!

**Comment by robin-vagner** [comment]
Thank you very much, in the meantime we froze our git-changelog version so there is no particular rush on our end 😄

**Comment by pawamoy** [comment]
Work in progress here: https://github.com/pawamoy/git-changelog/pull/80. I thought it was time to officially support PEP 440, not just SemVer. This will also allow us to support CalVer later, and maybe custom versioning schemes at some point.

**Comment by robin-vagner** [comment]
Just tried it out, it works perfectly. Thanks :)
